#!/bin/sh

echo "Running post-installation script"
# Add your post-install commands here
echo "Verifying banner file ownership:"
ls -l /etc/banner
opkg search /etc/banner

# Reboot the system to apply changes
echo "Rebooting the system..."
reboot