#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/upstream-daemon.sh
	procd_set_param directory /
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3 5 0
	procd_close_instance
}

stop_service() {
	rm -rf /tmp/upstream-daemon
}

status() {
	if pgrep -f "upstream-daemon.sh" >/dev/null; then
		echo "tollgate-upstream is running"
		return 0
	else
		echo "tollgate-upstream is not running"
		return 1
	fi
}
