package main

import (
	"fmt"
	"strings"
)

func generateCGI(schema *UISchema, structs map[string]*StructDef) string {
	var b strings.Builder

	b.WriteString("#!/bin/sh\n")
	b.WriteString("# /www/cgi-bin/tollgate-api - TollGate config API for LuCI\n")
	b.WriteString("# Auto-generated by luci-gen. Do not edit manually.\n\n")

	b.WriteString("CONFIG=\"/etc/tollgate/config.json\"\n")
	b.WriteString("IDENTITIES=\"/etc/tollgate/identities.json\"\n\n")

	writeCGIHelpers(&b)
	writeCGIParseQuery(&b)
	writeCGIDispatch(&b, schema, structs)

	return b.String()
}

func writeCGIHelpers(b *strings.Builder) {
	b.WriteString(cgiHelpersBlock)
}

const cgiHelpersBlock = `json_header() {
    printf "Content-Type: application/json\r\n\r\n"
}

json_esc() {
    tr -d '\000-\010\013\014\016-\037' | awk '
    BEGIN { ORS=""; printf "\"" }
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
    }
    NR > 1 { printf "\\n" }
    { printf "%s", $0 }
    END { printf "\"" }
    '
}

run_cmd() {
    "$@" 2>&1 || true
}

get_logs() {
    logread 2>/dev/null | grep 'daemon.err tollgate-wrt' | tail -n 300 | sed -E 's/^.*tollgate-wrt\[[0-9]+\]: //' || true
}

`

func writeCGIParseQuery(b *strings.Builder) {
	b.WriteString(cgiParseBlock)
}

const cgiParseBlock = `action=""
qs="${QUERY_STRING:-}"
old_ifs="$IFS"
IFS="&"
for p in $qs; do
    k="${p%%=*}"
    v="${p#*=}"
    case "$k" in
        action) action="$v" ;;
    esac
done
IFS="$old_ifs"

body=""
if [ "${CONTENT_LENGTH:-0}" -gt 0 ] 2>/dev/null; then
    body=$(dd bs=1 count="$CONTENT_LENGTH" 2>/dev/null)
fi

`

func writeCGIDispatch(b *strings.Builder, schema *UISchema, structs map[string]*StructDef) {
	b.WriteString("case \"$action\" in\n\n")

	writeCGIReadAction(b)
	writeCGILogsAction(b)
	writeCGIValidateAction(b, schema, structs)
	writeCGISaveAction(b, schema)
	writeCGIWalletFundAction(b)
	writeCGINetworkActions(b)
	writeCGIReadIdentitiesAction(b)
	writeCGISaveIdentitiesAction(b)
	writeCGIDefaultAction(b)

	b.WriteString("esac\n")
}

func writeCGIReadAction(b *strings.Builder) {
	b.WriteString(`read)
    cf=$(cat "$CONFIG" 2>/dev/null || echo "{}")
    idf=$(cat "$IDENTITIES" 2>/dev/null || echo "{}")
    wl=$(run_cmd /usr/bin/tollgate wallet balance)
    wi=$(run_cmd /usr/bin/tollgate wallet info)
    vr=$(run_cmd /usr/bin/tollgate version)
    st=$(run_cmd /usr/bin/tollgate status)
    lg=$(get_logs)

    json_header
    printf '{"ok":true,"config":%s,"identities":%s,"wallet":' "$cf" "$idf"
    printf '%s\n' "$wl" | json_esc
    printf ',"wallet_info":'
    printf '%s\n' "$wi" | json_esc
    printf ',"version":'
    printf '%s\n' "$vr" | json_esc
    printf ',"status":'
    printf '%s\n' "$st" | json_esc
    printf ',"logs":'
    printf '%s\n' "$lg" | json_esc
    printf '}'
    ;;

`)
}

func writeCGILogsAction(b *strings.Builder) {
	b.WriteString(`logs)
    lg=$(get_logs)
    json_header
    printf '{"ok":true,"logs":'
    printf '%s\n' "$lg" | json_esc
    printf '}'
    ;;

`)
}

func writeCGIValidateAction(b *strings.Builder, schema *UISchema, structs map[string]*StructDef) {
	b.WriteString("validate)\n")
	b.WriteString("    json_header\n\n")
	b.WriteString("    if ! printf '%s' \"$body\" | jsonfilter -q -e '$' >/dev/null 2>&1; then\n")
	b.WriteString("        printf '{\"ok\":false,\"errors\":[\"Invalid JSON.\"],\"warnings\":[]}'\n")
	b.WriteString("        exit 0\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    errs=\"\"\n")
	b.WriteString("    warns=\"\"\n\n")

	config := structs["Config"]
	if config == nil {
		return
	}

	for _, fd := range config.Fields {
		jsonKey := fd.JSONKey
		isArray := strings.HasPrefix(fd.GoType, "[]")
		isOmitempty := fd.Omitempty

		if isArray {
			if isOmitempty {
				fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing or not an array.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			} else {
				fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", jsonKey)
				fmt.Fprintf(b, "        errs=\"${errs}%s is missing or not an array.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			}
		} else if fd.GoType == "string" {
			if opts, ok := enumMap[jsonKey]; ok {
				fmt.Fprintf(b, "    %s_val=$(printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' 2>/dev/null) || true\n", jsonKey, jsonKey)
				fmt.Fprintf(b, "    if [ -z \"$%s_val\" ]; then\n", jsonKey)
				fmt.Fprintf(b, "        errs=\"${errs}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    else\n")
				fmt.Fprintf(b, "        case \"$%s_val\" in\n", jsonKey)
				for _, opt := range opts {
					fmt.Fprintf(b, "            %s) ;;\n", opt)
				}
				b.WriteString("            *) ")
				fmt.Fprintf(b, "errs=\"${errs}%s must be one of: %s.\\n\" ;;\n", jsonKey, strings.Join(opts, ", "))
				b.WriteString("        esac\n")
				b.WriteString("    fi\n\n")
			} else if isOmitempty {
				fmt.Fprintf(b, "    %s_val=$(printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' 2>/dev/null) || true\n", jsonKey, jsonKey)
				fmt.Fprintf(b, "    if [ -z \"$%s_val\" ]; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			} else {
				fmt.Fprintf(b, "    %s_val=$(printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' 2>/dev/null) || true\n", jsonKey, jsonKey)
				fmt.Fprintf(b, "    if [ -z \"$%s_val\" ]; then\n", jsonKey)
				fmt.Fprintf(b, "        errs=\"${errs}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			}
		} else if fd.GoType == "bool" {
			if isOmitempty {
				fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			}
		} else if fd.GoType == "uint64" || fd.GoType == "int" || fd.GoType == "float64" {
			if isOmitempty {
				fmt.Fprintf(b, "    %s_val=$(printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' 2>/dev/null) || true\n", jsonKey, jsonKey)
				fmt.Fprintf(b, "    if [ -z \"$%s_val\" ]; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			} else {
				fmt.Fprintf(b, "    %s_val=$(printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' 2>/dev/null) || true\n", jsonKey, jsonKey)
				fmt.Fprintf(b, "    if [ -z \"$%s_val\" ]; then\n", jsonKey)
				fmt.Fprintf(b, "        errs=\"${errs}%s is missing.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			}
		} else if isKnownStruct(structs, fd.GoType) {
			if isOmitempty {
				fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing or not an object.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			} else {
				fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", jsonKey)
				fmt.Fprintf(b, "        warns=\"${warns}%s is missing or not an object.\\n\"\n", jsonKey)
				b.WriteString("    fi\n\n")
			}
		}
	}

	b.WriteString("    if [ -z \"$errs\" ] && [ -z \"$warns\" ]; then\n")
	b.WriteString("        printf '{\"ok\":true,\"errors\":[],\"warnings\":[]}'\n")
	b.WriteString("    else\n")
	b.WriteString("        earr=\"\"\n")
	b.WriteString("        warr=\"\"\n")
	b.WriteString("        old_ifs=\"$IFS\"\n")
	b.WriteString("        IFS=\"\n\"\n")
	b.WriteString("        for line in $errs; do\n")
	b.WriteString("            [ -n \"$line\" ] && earr=\"${earr}\\\"${line}\\\",\"\n")
	b.WriteString("        done\n")
	b.WriteString("        for line in $warns; do\n")
	b.WriteString("            [ -n \"$line\" ] && warr=\"${warr}\\\"${line}\\\",\"\n")
	b.WriteString("        done\n")
	b.WriteString("        IFS=\"$old_ifs\"\n")
	b.WriteString("        earr=$(printf '%s' \"$earr\" | sed 's/,$//')\n")
	b.WriteString("        warr=$(printf '%s' \"$warr\" | sed 's/,$//')\n")
	b.WriteString("        printf '{\"ok\":%s,\"errors\":[%s],\"warnings\":[%s]}' \\\n")
	b.WriteString("            $([ -z \"$errs\" ] && echo \"true\" || echo \"false\") \\\n")
	b.WriteString("            \"$earr\" \"$warr\"\n")
	b.WriteString("    fi\n")
	b.WriteString("    ;;\n\n")
}

func writeCGISaveAction(b *strings.Builder, schema *UISchema) {
	b.WriteString(`save)
    json_header

    if ! printf '%s' "$body" | jsonfilter -q -e '$' >/dev/null 2>&1; then
        printf '{"ok":false,"error":"Invalid JSON.","errors":["Invalid JSON."],"warnings":[]}'
        exit 0
    fi

    save_errs=""
`)

	for i := range schema.Sections {
		sec := &schema.Sections[i]
		if sec.IsArray {
			fmt.Fprintf(b, "    if ! printf '%%s' \"$body\" | jsonfilter -q -e '$.%s' >/dev/null 2>&1; then\n", sec.JSONKey)
			fmt.Fprintf(b, "        save_errs=\"${save_errs}%s is required.\\n\"\n", sec.JSONKey)
			b.WriteString("    fi\n")
		}
	}

	b.WriteString(`
    if [ -n "$save_errs" ]; then
        earr=""
        old_ifs="$IFS"
        IFS="
"
        for line in $save_errs; do
            [ -n "$line" ] && earr="${earr}\"${line}\","
        done
        IFS="$old_ifs"
        earr=$(printf '%s' "$earr" | sed 's/,$//')
        printf '{"ok":false,"error":"Validation failed.","errors":[%s],"warnings":[]}' "$earr"
        exit 0
    fi

    ts=$(date +%Y%m%d-%H%M%S)
    bak="${CONFIG}.bak.${ts}"

    if [ -f "$CONFIG" ]; then
        cp "$CONFIG" "$bak" 2>/dev/null || {
            printf '{"ok":false,"error":"Failed to create backup: %s"}' "$bak"
            exit 0
        }
    fi

    tmp="${CONFIG}.tmp.$$"
    printf '%s\n' "$body" > "$tmp" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        printf '{"ok":false,"error":"Failed to write temporary file."}'
        exit 0
    }

    mv "$tmp" "$CONFIG" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        printf '{"ok":false,"error":"Failed to replace config file."}'
        exit 0
    }

    st=$(run_cmd /usr/bin/tollgate status)
    printf '{"ok":true,"message":"Saved config.json","backup":"%s","status":' "$bak"
    printf '%s\n' "$st" | json_esc
    printf '}'
    ;;

`)
}

func writeCGIWalletFundAction(b *strings.Builder) {
	b.WriteString(cgiWalletFundBlock)
}

const cgiWalletFundBlock = `wallet_fund)
    json_header
    token=$(printf '%s' "$body" | jsonfilter -q -e '$.token' 2>/dev/null) || true
    if [ -z "$token" ]; then
        printf '{"ok":false,"error":"Missing token field in request body."}'
        exit 0
    fi
    result=$(printf '%s\n' "$token" | /usr/bin/tollgate wallet fund 2>&1 || true)
    if echo "$result" | grep -qi "successfully funded"; then
        amt=$(echo "$result" | sed -n 's/.*with \([0-9]*\) sats.*/\1/p')
        printf '{"ok":true,"message":'
        printf '%s' "$result" | json_esc
        printf ',"amount_received":%s}' "${amt:-0}"
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

`

func writeCGINetworkActions(b *strings.Builder) {
	b.WriteString(cgiNetworkBlock)
}

const cgiNetworkBlock = `network_status)
    json_header
    result=$(run_cmd /usr/bin/tollgate network private status)
    ssid=$(echo "$result" | sed -n 's/^SSID: *\([^ ]*\)/\1/p')
    pw=$(echo "$result" | sed -n 's/^Password: *\([^ ]*\)/\1/p')
    en=$(echo "$result" | sed -n 's/^Status: *\(.*\)/\1/p')
    if [ -n "$ssid" ]; then
        printf '{"ok":true,"ssid":'
        printf '%s' "$ssid" | json_esc
        printf ',"password":'
        printf '%s' "${pw:-}" | json_esc
        printf ',"enabled":%s}' "$([ "$en" = "Enabled" ] && echo "true" || echo "false")"
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

network_enable)
    json_header
    result=$(run_cmd /usr/bin/tollgate network private enable)
    if echo "$result" | grep -q "successfully"; then
        printf '{"ok":true,"message":'
        printf '%s' "$result" | json_esc
        printf '}'
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

network_disable)
    json_header
    result=$(printf 'y\n' | /usr/bin/tollgate network private disable 2>&1 || true)
    if echo "$result" | grep -q "successfully"; then
        printf '{"ok":true,"message":'
        printf '%s' "$result" | json_esc
        printf '}'
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

network_rename)
    json_header
    new_ssid=$(printf '%s' "$body" | jsonfilter -q -e '$.ssid' 2>/dev/null) || true
    if [ -z "$new_ssid" ]; then
        printf '{"ok":false,"error":"Missing ssid field in request body."}'
        exit 0
    fi
    result=$(run_cmd /usr/bin/tollgate network private rename "$new_ssid")
    if echo "$result" | grep -q "successfully"; then
        printf '{"ok":true,"message":'
        printf '%s' "$result" | json_esc
        printf '}'
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

network_set_password)
    json_header
    new_pw=$(printf '%s' "$body" | jsonfilter -q -e '$.password' 2>/dev/null) || true
    if [ -z "$new_pw" ]; then
        result=$(run_cmd /usr/bin/tollgate network private set-password)
    else
        result=$(run_cmd /usr/bin/tollgate network private set-password "$new_pw")
    fi
    if echo "$result" | grep -q "successfully"; then
        gen_pw=$(echo "$result" | sed -n 's/.*password changed successfully//p')
        printf '{"ok":true,"message":'
        printf '%s' "$result" | json_esc
        if [ -z "$new_pw" ] && echo "$result" | grep -q ":"; then
            rand_pw=$(echo "$result" | grep -oE '[A-Z][a-z]+-[A-Z][a-z]+-[A-Z][a-z]+-[0-9]+' | head -1)
            if [ -n "$rand_pw" ]; then
                printf ',"new_password":'
                printf '%s' "$rand_pw" | json_esc
            fi
        fi
        printf '}'
    else
        printf '{"ok":false,"error":'
        printf '%s' "$result" | json_esc
        printf '}'
    fi
    ;;

`

func writeCGIReadIdentitiesAction(b *strings.Builder) {
	b.WriteString(`read_identities)
    idf=$(cat "$IDENTITIES" 2>/dev/null || echo "{}")
    json_header
    printf '{"ok":true,"identities":%s}' "$idf"
    ;;

`)
}

func writeCGISaveIdentitiesAction(b *strings.Builder) {
	b.WriteString(`save_identities)
    json_header

    if ! printf '%s' "$body" | jsonfilter -q -e '$' >/dev/null 2>&1; then
        printf '{"ok":false,"error":"Invalid JSON."}'
        exit 0
    fi

    if ! printf '%s' "$body" | jsonfilter -q -e '$.public_identities' >/dev/null 2>&1; then
        printf '{"ok":false,"error":"public_identities is required."}'
        exit 0
    fi

    ts=$(date +%Y%m%d-%H%M%S)
    bak="${IDENTITIES}.bak.${ts}"

    if [ -f "$IDENTITIES" ]; then
        cp "$IDENTITIES" "$bak" 2>/dev/null || {
            printf '{"ok":false,"error":"Failed to create backup: %s"}' "$bak"
            exit 0
        }
    fi

    tmp="${IDENTITIES}.tmp.$$"
    printf '%s\n' "$body" > "$tmp" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        printf '{"ok":false,"error":"Failed to write temporary file."}'
        exit 0
    }

    mv "$tmp" "$IDENTITIES" 2>/dev/null || {
        rm -f "$tmp" 2>/dev/null
        printf '{"ok":false,"error":"Failed to replace identities file."}'
        exit 0
    }

    printf '{"ok":true,"message":"Saved identities.json","backup":"%s"}' "$bak"
    ;;

`)
}

func writeCGIDefaultAction(b *strings.Builder) {
	b.WriteString(`*)
    json_header
    printf '{"ok":false,"error":"Unknown action: %s"}' "${action:-none}"
    ;;

`)
}

func isKnownStruct(structs map[string]*StructDef, name string) bool {
	_, ok := structs[name]
	return ok
}
